version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    ports:
      - 127.0.0.1:27017:27017

volumes:
  db-data:
  mongo-config:
