version: '3'

services:
  db:
    container_name: postgres_server # use it as hostname to cinnect with pgadmin
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p8cti5y6u%mo4tRQZM # randomly generated, please change
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  pgadmin:
    container_name: pgadmin4_web
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: some_account@some_domain.org
      PGADMIN_DEFAULT_PASSWORD: PnFM68M3$MXEBLJ7nVkr # randomly generated, please change
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  db_data:
  pgadmin_data:
